# Client Portal - App Engine Configuration
runtime: nodejs20
service: portal-dev

# Instance configuration
instance_class: F2

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  NEXT_PUBLIC_STRAPI_URL: "https://cms-dev-dot-secret-rope-485200-h6.nn.r.appspot.com"
  NEXT_PUBLIC_API_URL: "https://cms-dev-dot-secret-rope-485200-h6.nn.r.appspot.com/api"
  JJ_PORTAL_CAPTCHA_KEY: "6LdhjlYsAAAAAN-C1EmNPoePjQ--ZlfyrwPD8HrH"

automatic_scaling:
  min_instances: 0
  max_instances: 3
  min_idle_instances: 0
  target_cpu_utilization: 0.65

build_env_variables:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_STRAPI_URL: "https://cms-dev-dot-secret-rope-485200-h6.nn.r.appspot.com"
  NEXT_PUBLIC_API_URL: "https://cms-dev-dot-secret-rope-485200-h6.nn.r.appspot.com/api"
  JJ_PORTAL_CAPTCHA_KEY: "6LdhjlYsAAAAAN-C1EmNPoePjQ--ZlfyrwPD8HrH"
